package io.github.fortunen.kete;

import java.net.URI;
import java.util.Locale;
import java.util.UUID;

import org.apache.commons.configuration2.MapConfiguration;
import org.keycloak.models.KeycloakSession;
import org.keycloak.services.managers.ClientManager;
import org.keycloak.services.managers.RealmManager;

import com.nimbusds.oauth2.sdk.ClientCredentialsGrant;
import com.nimbusds.oauth2.sdk.Scope;
import com.nimbusds.oauth2.sdk.TokenRequest;
import com.nimbusds.oauth2.sdk.auth.ClientSecretBasic;
import com.nimbusds.oauth2.sdk.auth.Secret;
import com.nimbusds.oauth2.sdk.id.ClientID;
import com.nimbusds.oauth2.sdk.token.AccessToken;

import io.github.fortunen.kete.utils.JwtUtils;
import io.github.fortunen.kete.utils.ValidationUtils;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.SneakyThrows;
import lombok.ToString;
import lombok.extern.slf4j.Slf4j;

@Data
@Slf4j
@SuppressWarnings("deprecation")
@NoArgsConstructor(access = lombok.AccessLevel.PRIVATE)
@AllArgsConstructor(access = lombok.AccessLevel.PRIVATE)
@EqualsAndHashCode(exclude = {"tokenHolder"})
@ToString(exclude = {"clientSecret", "tokenHolder", "autoRegisteredClientSecret"})
public class OAuthMaterial {

	public static final String MODE = "mode";
	public static final String SCOPE = "scope";
	public static final String REALM = "realm";
	public static final String ENABLED = "enabled";
	public static final String TOKEN_URL = "token-url";
	public static final String CLIENT_ID = "client-id";
	public static final String CLIENT_SECRET = "client-secret";



	public static final String DEFAULT_INTERNAL_CLIENT_ID = Constants.ID + "-oauth-client";
	public static final String DEFAULT_INTERNAL_TOKEN_URL_TEMPLATE = "http://localhost:8080/realms/${realm}/protocol/openid-connect/token";

	public enum OAuthMode {
		INTERNAL,
		EXTERNAL
	}

	private Scope scope;
	private URI tokenUri;
	private String realm;
	private OAuthMode mode;
	private boolean enabled;
	private ClientID clientId;
	private Secret clientSecret;
	private boolean clientRegistered;
	private boolean autoGeneratedSecret;
	private String autoRegisteredClientId;
	private String autoRegisteredClientSecret;
	private transient final JwtUtils.CachedTokenHolder tokenHolder = new JwtUtils.CachedTokenHolder();

	public static OAuthMaterialBuilder builder() {
		return new OAuthMaterialBuilder();
	}

	public boolean isInternalMode() {
		return mode == OAuthMode.INTERNAL;
	}

	public boolean requiresClientRegistration() {
		return enabled && isInternalMode() && !clientRegistered && autoGeneratedSecret;
	}

	public void markClientRegistered() {
		this.clientRegistered = true;
	}

	public AccessToken getAccessToken() {

		if (!enabled) {
			return null;
		}

		return tokenHolder.getToken(() -> {

			var grant = new ClientCredentialsGrant();
			var clientAuth = new ClientSecretBasic(clientId, clientSecret);

			return ValidationUtils.isNotNull(scope) ? new TokenRequest(tokenUri, clientAuth, grant, scope) : new TokenRequest(tokenUri, clientAuth, grant);
		});
	}

	public boolean registerInternalClient(KeycloakSession session) {

		ValidationUtils.requireNonNull(session, "session is required");

		if (!enabled) {
			return true; // not enabled, nothing to register
		}

		if (!isInternalMode()) {
			return true; // not internal mode, nothing to register
		}

		if (clientRegistered) {
			return true; // already registered
		}

		ValidationUtils.requireNonBlank(realm, "realm is required for INTERNAL OAuth mode");

		var realmModel = session.realms().getRealmByName(realm);

		if (ValidationUtils.isNull(realmModel)) {
			log.warn("Realm not found for OAuth client registration: " + realm);
			return false;
		}

		var clientIdValue = autoRegisteredClientId;
		var clientSecretValue = autoRegisteredClientSecret;

		// Check if client already exists

		var existingClient = realmModel.getClientByClientId(clientIdValue);

		if (ValidationUtils.isNotNull(existingClient)) {
			markClientRegistered();
			return true;
		}

		try {

			// client

			var client = realmModel.addClient(clientIdValue);

			client.setClientId(clientIdValue);
			client.setSecret(clientSecretValue);
			client.setEnabled(true);
			client.setServiceAccountsEnabled(true); // Enable client credentials grant
			client.setPublicClient(false); // Confidential client
			client.setDirectAccessGrantsEnabled(false);
			client.setStandardFlowEnabled(false);
			client.setProtocol("openid-connect");
			client.setClientAuthenticatorType("client-secret");

			// client service account

			new ClientManager(new RealmManager(session)).enableServiceAccount(client);

			markClientRegistered();

			// return

			return true;

		} catch (Exception e) {
			log.warn("Failed to register OAuth client in realm " + realm, e);
			return false;
		}
	}

	public static class OAuthMaterialBuilder {

		private String keycloakRealm;
		private KeycloakSession keycloakSession;
		private OAuthMaterial material = new OAuthMaterial();

		public OAuthMaterialBuilder withEnabled(boolean enabled) {
			this.material.enabled = enabled;
			return this;
		}

		public OAuthMaterialBuilder withMode(OAuthMode mode) {
			this.material.mode = mode;
			return this;
		}

		public OAuthMaterialBuilder withTokenUri(URI tokenUri) {
			this.material.tokenUri = tokenUri;
			return this;
		}

		public OAuthMaterialBuilder withClientId(String clientId) {
			this.material.clientId = new ClientID(clientId);
			return this;
		}

		public OAuthMaterialBuilder withClientSecret(String clientSecret) {
			this.material.clientSecret = new Secret(clientSecret);
			return this;
		}

		public OAuthMaterialBuilder withScope(String scope) {

			if (ValidationUtils.isNotBlank(scope)) {
				this.material.scope = Scope.parse(scope.trim());
			}

			return this;
		}

		public OAuthMaterialBuilder withRealm(String realm) {
			this.material.realm = realm;
			return this;
		}

		public OAuthMaterialBuilder withKeycloakRealm(String keycloakRealm) {
			this.keycloakRealm = keycloakRealm;
			return this;
		}

		public OAuthMaterialBuilder withKeycloakSession(KeycloakSession keycloakSession) {
			this.keycloakSession = keycloakSession;
			return this;
		}

		@SneakyThrows
		public OAuthMaterialBuilder withConfiguration(MapConfiguration configuration) {

			ValidationUtils.requireNonNull(configuration, "configuration is required");

			// enabled

			material.enabled = configuration.getBoolean(ENABLED, false);

			if (!material.enabled) {
				return this;
			}

			// mode

			var modeStr = configuration.getString(MODE, OAuthMode.EXTERNAL.name()).trim().toUpperCase(Locale.ROOT);

			material.mode = ValidationUtils.tryParseEnum(OAuthMode.class, modeStr, true).orElse(OAuthMode.EXTERNAL);

			// scope

			var scopeStr = configuration.getString(SCOPE, "").trim();

			if (ValidationUtils.isNotBlank(scopeStr)) {
				material.scope = Scope.parse(scopeStr);
			}

			// configure

			if (material.mode == OAuthMode.INTERNAL) {
				configureInternalMode(configuration);
			} else {
				configureExternalMode(configuration);
			}

			// return

			return this;
		}

		private void configureInternalMode(MapConfiguration configuration) {

			// realm

			var realm = configuration.getString(REALM, "").trim();

			if (ValidationUtils.isBlank(realm)) {
				realm = keycloakRealm;
			}

			ValidationUtils.requireNonBlank(realm, REALM + " is required for INTERNAL mode (either in OAuth config or route config)");

			material.realm = realm;

			// token url

			var tokenUrl = configuration.getString(TOKEN_URL, "").trim();

			if (ValidationUtils.isBlank(tokenUrl)) {
				tokenUrl = DEFAULT_INTERNAL_TOKEN_URL_TEMPLATE.replace("${realm}", realm);
			}

			material.tokenUri = URI.create(tokenUrl);

			// client id

			var clientId = configuration.getString(CLIENT_ID, "").trim();

			if (ValidationUtils.isBlank(clientId)) {
				clientId = DEFAULT_INTERNAL_CLIENT_ID;
			}

			material.clientId = new ClientID(clientId);
			material.autoRegisteredClientId = clientId;

			// client secret

			var clientSecret = configuration.getString(CLIENT_SECRET, "").trim();

			if (ValidationUtils.isBlank(clientSecret)) {
				clientSecret = UUID.randomUUID().toString().toLowerCase(Locale.ROOT);
				material.autoGeneratedSecret = true;
			}

			material.clientSecret = new Secret(clientSecret);
			material.autoRegisteredClientSecret = clientSecret;
		}

		private void configureExternalMode(MapConfiguration configuration) {

			var tokenUrl = ValidationUtils.requireNonBlank(configuration.getString(TOKEN_URL, "").trim(), TOKEN_URL + " is required when mode is EXTERNAL");
			var clientId = ValidationUtils.requireNonBlank(configuration.getString(CLIENT_ID, "").trim(), CLIENT_ID + " is required when mode is EXTERNAL");
			var clientSecret = ValidationUtils.requireNonBlank(configuration.getString(CLIENT_SECRET, "").trim(), CLIENT_SECRET + " is required when mode is EXTERNAL");

			material.tokenUri = URI.create(tokenUrl);
			material.clientId = new ClientID(clientId);
			material.clientSecret = new Secret(clientSecret);
		}

		public OAuthMaterial build() {

			// mode

			if (material.enabled && ValidationUtils.isNull(material.mode)) {
				material.mode = OAuthMode.INTERNAL;
			}

			// register

			if (material.requiresClientRegistration() && ValidationUtils.isNotNull(keycloakSession)) {
				material.registerInternalClient(keycloakSession);
			}

			// return

			return material;
		}
	}
}
