services:

  emqx:
    image: emqx/emqx:latest
    ports:
      - 1883:1883
      - 18083:18083
    environment:
      EMQX_ALLOW_ANONYMOUS: "true"
      EMQX_AUTHORIZATION__NO_MATCH: allow
      EMQX_AUTHORIZATION__SOURCES: "[]"
    healthcheck:
      test: ["CMD", "emqx_ctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 30

  keycloak:
    image: ghcr.io/fortunen/kete/quick-start-keycloak
    command: start-dev
    ports:
      - 8080:8080
    environment:
      kete.routes.quick-start.destination.kind: mqtt-3
      kete.routes.quick-start.destination.host: emqx
      kete.routes.quick-start.destination.port: 1883
      kete.routes.quick-start.destination.topic: keycloak-events
    depends_on:
      emqx:
        condition: service_healthy
