{
  "type": "record",
  "name": "AdminEvent",
  "namespace": "io.github.fortunen.kete.events",
  "fields": [
    { "name": "id",              "type": ["null", "string"], "default": null },
    { "name": "time",            "type": ["null", "long"],   "default": null },
    { "name": "realm_id",        "type": ["null", "string"], "default": null },
    { "name": "realm_name",      "type": ["null", "string"], "default": null },
    {
      "name": "auth_details",
      "type": ["null", {
        "type": "record",
        "name": "AuthDetails",
        "fields": [
          { "name": "realm_id",   "type": ["null", "string"], "default": null },
          { "name": "realm_name", "type": ["null", "string"], "default": null },
          { "name": "client_id",  "type": ["null", "string"], "default": null },
          { "name": "user_id",    "type": ["null", "string"], "default": null },
          { "name": "ip_address", "type": ["null", "string"], "default": null }
        ]
      }],
      "default": null
    },
    { "name": "resource_type",   "type": ["null", "string"], "default": null },
    { "name": "operation_type",  "type": ["null", "string"], "default": null },
    { "name": "resource_path",   "type": ["null", "string"], "default": null },
    { "name": "representation",  "type": ["null", "string"], "default": null },
    { "name": "error",           "type": ["null", "string"], "default": null },
    { "name": "details",         "type": ["null", { "type": "map", "values": "string" }], "default": null }
  ]
}
