package io.github.fortunen.kete.unittests.oauthmaterial;

import static org.assertj.core.api.Assertions.assertThat;

import io.github.fortunen.kete.OAuthMaterial;
import java.util.HashMap;
import org.apache.commons.configuration2.MapConfiguration;
import org.junit.jupiter.api.Test;

class requiresClientRegistrationTests {

	@Test
	void shouldReturnTrueWhenEnabledAndInternalModeWithAutoGeneratedSecret() {

		// arrange

		var map = new HashMap<String, Object>();
		map.put("enabled", "true");
		map.put("mode", "internal");
		map.put("realm", "test-realm");
		// No client-secret provided → auto-generated
		var config = new MapConfiguration(map);

		var oauth = OAuthMaterial.builder()
			.withConfiguration(config)
			.build();

		// act

		var result = oauth.requiresClientRegistration();

		// assert

		assertThat(result)
			.as("Should require registration when enabled, internal mode, not registered, and auto-generated secret")
			.isTrue();
	}

	@Test
	void shouldReturnFalseWhenDisabled() {

		// arrange

		var map = new HashMap<String, Object>();
		map.put("enabled", "false");
		var config = new MapConfiguration(map);

		var oauth = OAuthMaterial.builder()
			.withConfiguration(config)
			.build();

		// act

		var result = oauth.requiresClientRegistration();

		// assert

		assertThat(result)
			.as("Should not require registration when disabled")
			.isFalse();
	}

	@Test
	void shouldReturnFalseWhenExternalMode() {

		// arrange

		var map = new HashMap<String, Object>();
		map.put("enabled", "true");
		map.put("mode", "external");
		map.put("token-url", "http://localhost/token");
		map.put("client-id", "my-client");
		map.put("client-secret", "my-secret");
		var config = new MapConfiguration(map);

		var oauth = OAuthMaterial.builder()
			.withConfiguration(config)
			.build();

		// act

		var result = oauth.requiresClientRegistration();

		// assert

		assertThat(result)
			.as("Should not require registration when external mode")
			.isFalse();
	}

	@Test
	void shouldReturnFalseWhenClientSecretExplicitlyProvided() {

		// arrange

		var map = new HashMap<String, Object>();
		map.put("enabled", "true");
		map.put("mode", "internal");
		map.put("realm", "test-realm");
		map.put("client-secret", "explicit-secret"); // Explicitly provided
		var config = new MapConfiguration(map);

		var oauth = OAuthMaterial.builder()
			.withConfiguration(config)
			.build();

		// act

		var result = oauth.requiresClientRegistration();

		// assert

		assertThat(result)
			.as("Should not require registration when client secret is explicitly provided")
			.isFalse();
	}

	@Test
	void shouldReturnFalseWhenAlreadyRegistered() {

		// arrange

		var map = new HashMap<String, Object>();
		map.put("enabled", "true");
		map.put("mode", "internal");
		map.put("realm", "test-realm");
		var config = new MapConfiguration(map);

		var oauth = OAuthMaterial.builder()
			.withConfiguration(config)
			.build();

		oauth.markClientRegistered(); // Mark as already registered

		// act

		var result = oauth.requiresClientRegistration();

		// assert

		assertThat(result)
			.as("Should not require registration when already registered")
			.isFalse();
	}
}
